<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>OTCode.Core</RootNamespace>
    <AssemblyName>OTCode.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>